### ISSUE TITLE
Use Webpacker to compile JS assets

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#64]
In GitLab by @bzk60 on Jul 16, 2018, 15:25

https://github.com/projectblacklight/blacklight/wiki/Using-Webpacker-to-compile-javascript-assets    
https://www.npmjs.com/package/blacklight-frontend

* [x] ~~Get typeahead working~~ see #65 
* [x] Popper is not loading when using webpacker  
Fixed using the solution from here: https://github.com/twbs/bootstrap/issues/23381#issuecomment-322179061
* [x] ~~Get Bookmark toogle working~~ see #70 
* [x] ~~Get checkbox submit working~~ see #71 
* [x] ~~Figure out how to deploy to production https://webpack.js.org/guides/production/~~ see #25

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 17, 2018, 08:12

@bzk60, will you be looking into...


![Sprockets](https://i.ytimg.com/vi/QHZR9SA5pOg/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB9wmcKF6Vnaxu8VhmanLR2YbIPpg)

?

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:10

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:11

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:12

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:40

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:44

changed title from **{-Investigate Webpacker-}** to **{+Use Webpacker to compile JS assets+}**

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:44

assigned to @cdm32

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:45

added ~938 label

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:45

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:46

@cdm32 nope since now that you got the assets loaded using webpacker :)

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:49

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:49

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018, 09:50

changed the description

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 17, 2018 9:46

@cdm32 nope since now that you got the assets loaded using webpacker :)

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 17, 2018 9:50

this was the missing piece: https://github.com/twbs/bootstrap/issues/23381#issuecomment-322179061

everything else wasn't needed

i told justin coyne about it, hopefully he will update https://github.com/projectblacklight/blacklight/wiki/Using-Webpacker-to-compile-javascript-assets

i guess i could but that seems out of step

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 17, 2018 13:40

two things ain't working still:

```
// require('blacklight-frontend/app/javascript/blacklight/checkbox_submit')
// require('blacklight-frontend/app/javascript/blacklight/bookmark_toggle')
```

uncommenting results in errors.

also we need to document dev instructions

also we need to know how to deploy to prod before we can call this done for real
