### ISSUE TITLE
Sunsetting CAT Todo

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#917]
- [x] Update home page
    - [x] Remove legacy CAT references in the catalog eg. link to the legacy cat in the home page (Ruth text)
- [x] Update about page (Ruth text)
- [x] Update 404
- [x] Update banner in config (not currently active): https://github.com/psu-libraries/psulib_blacklight/blob/main/config/locales/blacklight.en.yml#L8

**Comment by ruthtillman** [comment]
Note -- we're keeping the course reserves link for now https://github.com/psu-libraries/psulib_blacklight/blob/main/app/views/shared/_user_util_links.html.erb

**Comment by ruthtillman** [comment]
Banner in config (not currently active): https://github.com/psu-libraries/psulib_blacklight/blob/main/config/locales/blacklight.en.yml#L8 maybe we just remove this for now?

**Comment by ruthtillman** [comment]
Error/404 page: https://github.com/psu-libraries/psulib_blacklight/blob/main/app/views/errors/not_found.html.erb

Change to:

```
<h4>The page you were looking for doesn't exist.</h4>
<p>You may have mistyped the address or the page may have moved.</p>
<p>Try searching again, use <%=link_to 'advanced search', 'https://catalog.libraries.psu.edu/advanced' %>, or check out our <%= link_to 'search tips page', 'https://catalog.libraries.psu.edu/search_tips' %> to learn more about finding things in the catalog. If you need more assistance, <%= link_to 'Ask a Librarian', 'https://libraries.psu.edu/ask/' %>.</p>
```

**Comment by ruthtillman** [comment]
Home page: https://github.com/psu-libraries/psulib_blacklight/blob/main/app/views/catalog/_home_text.html.erb

I updated a couple other links too.

```
<h1><%= t('blacklight.application_name') %></h1>
<p class="lead">Read more about <%= link_to "the work we've been doing to improve your search experience", page_path('about') %>.</p>
<p>You can also:</p>
<ul>
  <li><%= link_to 'Learn more', page_path('search_tips') %> about searching the catalog</li>
  <li><%= link_to 'Ask a Librarian', 'https://libraries.psu.edu/ask' %> for help finding materials</li>
  <li><%= link_to 'Send us feedback', 'https://libraries.psu.edu/website-feedback' %> on how we can improve your experience</li>
</ul>

<h2>Other Library Resources</h2>
<ul class="list-inline">
  <li class="list-inline-item"><%= link_to 'LionSearch (Articles)', 'https://psu.summon.serialssolutions.com/' %></li>
  <li class="list-inline-item"><%= link_to 'Databases', 'https://libraries.psu.edu/databases' %></li>
  <li class="list-inline-item"><%= link_to 'E-journals', 'https://sk8es4mc2l.search.serialssolutions.com/ejp/?libHash=SK8ES4MC2L#/search/?searchControl=title&searchType=a_to_z&criteria=A&language=en-US&titleType=JOURNALS' %></li>
  <li class="list-inline-item"><%= link_to 'Digital Collections', 'https://digital.libraries.psu.edu/' %></li>
  <li class="list-inline-item"><%= link_to 'Archival Collections', 'https://aspace.libraries.psu.edu/' %></li>
</ul>
```

**Comment by ruthtillman** [comment]
Home page: 

```
<h1>About</h1>

<p>The Library Catalog is the place to search for library materials, including: books, journals, government documents, newspapers, maps, archival collections, music, videos, conference proceedings, and more. Want to learn better ways to search? Check out our <%= link_to 'search tips', 'search_tips' %>.</p>

<p>You can have materials held for you at most locations by clicking "I Want It!" or use links in the record to access them online. You may need to login through WebAccess or be on a Penn State VPN in order to access online materials. <%= link_to 'Report problems or give us feedback', 'https://libraries.psu.edu/website-feedback' %>.</p>

<h2>What You Can Find Elsewhere</h2>

<ul>
  <li>Individual articles. Try using <%= link_to 'LionSearch', 'https://psu.summon.serialssolutions.com/' %> or a <%= link_to 'database', 'https://libraries.psu.edu/databases' %> on the subject.</li>
  <li>Digital collections. Search or browse our <%= link_to 'digital collections', 'https://digital.libraries.psu.edu/digital/search' %> to find records, maps, images, and more.</li>
  <li>Archival Collections. Search our <%= link_to 'archival collections', 'https://aspace.libraries.psu.edu/' %> find unique historical materials held by our libraries.</li>
  <li>Books, journal articles, and other materials we don't own. Use our <%= link_to 'Interlibrary Loan services', 'https://libraries.psu.edu/services/interlibrary-loan-services' %> to request these materials.</li>
</ul>

<h2>FAQ</h2>

<p>Here are some of the questions we've gotten about the Catalog:</p>

<p><strong>What about the CAT?</strong> Because the CAT was created on aging software, it retired at the end of Fall 2021. <%= link_to 'Learn more about the CAT retiring', 'https://news.psu.edu/story/673627/2021/10/22/academics/libraries-completes-online-catalog-update-will-retire-cat' %>.</p>

<p><strong>Can I find the same material as the CAT?</strong> Yes. The records in the Catalog and the legacy CAT are exactly the same.</p>

<p><strong>Is this replacing Lionsearch/Summon?</strong> No, but you will notice that "view in classic catalog" and "I Want It" links in Lionsearch point here instead of to the legacy CAT.</p>
```

**Comment by banukutlu** [comment]
> Banner in config (not currently active): https://github.com/psu-libraries/psulib_blacklight/blob/main/config/locales/blacklight.en.yml#L8 maybe we just remove this for now?

@ruthtillman Could you give me a new updated text for this, since it is used as a default one?

**Comment by ruthtillman** [comment]
If we should have some kind of text--I don't anticipate every displaying this, but let's just put up a welcome! `Welcome to the Penn State Libraries Catalog!`
